import LiveChatBot from '@/components/chat/LiveChatBot';
import SideBarNav from '@/components/nav/SideBarNav';
import TopNav from '@/components/nav/TopNav';
import type { Metadata } from 'next';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
	title: 'Admin Dash',
	description: 'Generated by create next app',
};

export default async function AuthenticatedLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<SideBarNav />
			<div className='md:ml-56'>
				<TopNav />

				<main className='p-6'>
					{children}
					<LiveChatBot />
				</main>
			</div>
		</>
	);
}
